server:
  port: 9000

spring:
  application:
    name: passport
  cloud:
    nacos:
      discovery: #Nacos注册中心地址
        server-addr: localhost:8848
  redis:
    host: 192.168.142.132
    port: 6379
    database: 0

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
jwt:
  config:
    key: codelife
    ttl: 36000000
feign:
  hystrix:
    enabled: true